### ISSUE TITLE
Thumbnail images in map popup don't work

### ISSUE THREAD

**Issue by hou098** [BioplatformsAustralia/bpaotu#213]
To reproduce:
- Go to https://data.bioplatforms.com/bpa/otu
- Click "Interactive map search"
- Zoom in on eastern Tasmania (see screenshot below)
- Click the marker at -42.0154 147.49095
- Thumbnail images should appear at the top of the marker popup as the content of each `<a>` . The browser falls back to showing the `alt` text "Australian Microbiome"

![Screenshot from 2022-05-19 11-03-53](https://user-images.githubusercontent.com/93953122/169180605-931ee535-6dd4-4a32-b0b8-cb98fbb8ec39.png)

The map  popup is supposed to have some thumbnails at the top, but they don't appear.

In production, this is what happens when you try to view one of those thumbnail URLs directly

https://data.bioplatforms.com/bpa/otu/private/site-image-thumbnail/bpa-base-site-image-16013-16014/789c8e0096199d3c9db40dfd0bc4c10f

```
HTTP/2 301 Moved Permanently
server: nginx/1.16.1
date: Thu, 19 May 2022 01:00:33 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: /bpa/otu/private/site-image-thumbnail/bpa-base-site-image-16013-16014/789c8e0096199d3c9db40dfd0bc4c10f/
x-frame-options: DENY
strict-transport-security: max-age=10; includeSubDomains
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
X-Firefox-Spdy: h2
```
Redirects to https://data.bioplatforms.com/bpa/otu/private/site-image-thumbnail/bpa-base-site-image-16013-16014/789c8e0096199d3c9db40dfd0bc4c10f/

```
GET /bpa/otu/private/site-image-thumbnail/bpa-base-site-image-16013-16014/789c8e0096199d3c9db40dfd0bc4c10f/ HTTP/2
Host: data.bioplatforms.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://data.bioplatforms.com/bpa/otu
Connection: keep-alive
Cookie: csrftoken=pF8KNiwFQgLLzVgL6Pf3pfJYAxGmXMdKrrYpTZd0XjeZXhGvF6T43W6uP6JRIdXW; auth_tkt="00c888fb8261404723f67c6965cef8a06191eb09hou098!userid_type=unicode"; auth_tkt="00c888fb8261404723f67c6965cef8a06191eb09hou098!userid_type=unicode"; ckan=fc4398af950bc6b9947f27be2a8ad68329302da5b612fa9589304de8abe06d55118f2980; _ga=GA1.2.808982441.1652679543
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
TE: trailers
```

```
HTTP/2 500 Internal Server Error
server: nginx/1.16.1
date: Thu, 19 May 2022 01:12:53 GMT
content-type: text/html; charset=utf-8
content-length: 2671
vary: Accept-Language, Cookie
content-language: en
x-frame-options: DENY
strict-transport-security: max-age=10; includeSubDomains
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
X-Firefox-Spdy: h2
```

I don't have access to the production server logs, but it also fails in the development environment

```
GET | http://localhost:3000/private/site-image-thumbnail/bpa-base-site-image-16013-16014/789c8e0096199d3c9db40dfd0bc4c10f

HTTP/1.1 301 Moved Permanently
X-Powered-By: Express
content-type: text/html; charset=utf-8
location: /private/site-image-thumbnail/bpa-base-site-image-16013-16014/789c8e0096199d3c9db40dfd0bc4c10f/
content-length: 0
x-frame-options: DENY
server: Werkzeug/0.16.1 Python/3.7.12
date: Thu, 19 May 2022 00:58:32 GMT
connection: keep-alive
Vary: Accept-Encoding
```
And then:

```
runserver_1     | 172.18.0.1 - - [19/May/2022 09:44:43] "GET /private/site-image-thumbnail/bpa-base-site-image-16013-16014/789c8e0096199d3c9db40dfd0bc4c10f/ HTTP/1.1" 500 -
runserver_1     | Traceback (most recent call last):
runserver_1     |   File "/env/lib/python3.7/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
runserver_1     |     return self.application(environ, start_response)
runserver_1     |   File "/env/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
runserver_1     |     response = self.get_response(request)
runserver_1     |   File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 75, in get_response
runserver_1     |     response = self._middleware_chain(request)
runserver_1     |   File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
runserver_1     |     response = response_for_exception(request, exc)
runserver_1     |   File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
runserver_1     |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
runserver_1     |   File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
runserver_1     |     return debug.technical_500_response(request, *exc_info)
runserver_1     |   File "/env/lib/python3.7/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
runserver_1     |     six.reraise(exc_type, exc_value, tb)
runserver_1     |   File "/env/lib/python3.7/site-packages/six.py", line 702, in reraise
runserver_1     |     raise value.with_traceback(tb)
runserver_1     |   File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
runserver_1     |     response = get_response(request)
runserver_1     |   File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
runserver_1     |     response = self.process_exception_by_middleware(e, request)
runserver_1     |   File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
runserver_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
runserver_1     |   File "/env/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
runserver_1     |     response = view_func(request, *args, **kwargs)
runserver_1     |   File "/app/bpaotu/bpaotu/views.py", line 1039, in site_image_thumbnail
runserver_1     |     buf, content_type = fetch_image(package_id, resource_id)
runserver_1     |   File "/app/bpaotu/bpaotu/site_images.py", line 108, in fetch_image
runserver_1     |     img_data = resize_image(r.content)
runserver_1     |   File "/app/bpaotu/bpaotu/site_images.py", line 85, in resize_image
runserver_1     |     with Image.open(BytesIO(content)) as img_obj:
runserver_1     |   File "/env/lib/python3.7/site-packages/PIL/Image.py", line 2818, in open
runserver_1     |     raise IOError("cannot identify image file %r" % (filename if filename else fp))
runserver_1     | OSError: cannot identify image file <_io.BytesIO object at 0x7f2760c71fb0>
```

That may be because there's currently no CKAN API key available during development. Something similar may be going wrong in production.

**Comment by hou098** [comment]
See https://github.com/BioplatformsAustralia/bpaotu/commit/d1fe638695b9a4fb5b4e1f25c1ff5988be1ee10d
At least it doesn't fail silently now
![Screenshot_2022-05-23_10-40-39](https://user-images.githubusercontent.com/93953122/169723755-188aaf45-06c4-4f34-bb29-4caecbb13d21.png)

**Comment by hou098** [comment]
Resolved (bad CKAN API key in production).
