### ISSUE TITLE
Galaxy integration bug: create_user was renamed to users.create

### ISSUE THREAD

**Issue by sztamas** [BioplatformsAustralia/bpaotu#36]
The `Submit to Galaxy` functionality is failing currently if the galaxy user doesn't exist.

The view is calling `galaxy_client.create_user` on the galaxy client, but the client has been changed so the new function is `galaxy_client.user.create`.

**Comment by sztamas** [comment]
The user is created now, but there is a bug on invoking `response.json()` on a `dict`.

```
Traceback (most recent call last):
  File "/app/bpaotu/bpaotu/views.py", line 595, in submit_to_galaxy
    response = _handle()
  File "/app/bpaotu/bpaotu/views.py", line 573, in _handle
    users_api_key = _get_users_galaxy_api_key(email)
  File "/app/bpaotu/bpaotu/views.py", line 557, in _get_users_galaxy_api_key
    galaxy_user = galaxy.users.create(email)
  File "/app/bpaotu/bpaotu/galaxy_client.py", line 66, in create
    return response.json()
```
